# Generated by Django 2.2.1 on 2019-07-11 10:30

from django.db import migrations, models
import screens.models.source


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='plays_everything',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=screens.models.source.get_file_path),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('FRM', 'IFrame')], max_length=3),
        ),
    ]
