# Generated by Django 2.2.1 on 2019-07-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_auto_20190711_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='interspersed_source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='screens.Source'),
        ),
    ]
