# Generated by Django 2.2.1 on 2019-07-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_remove_schedulebuilderdirective_ends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulebuilderdirective',
            old_name='recurrences',
            new_name='occurences',
        ),
    ]
