# Generated by Django 2.2.1 on 2019-07-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0003_playlist_interspersed_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='exclude_from_play_all',
            field=models.BooleanField(default=False),
        ),
    ]
