# Generated by Django 2.2.1 on 2019-07-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0003_auto_20190708_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulebuilderdirective',
            old_name='occurences',
            new_name='occurrences',
        ),
    ]
