# Generated by Django 2.2.1 on 2019-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0004_auto_20190708_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('IMG', 'Weekly'), (' VID', 'Monthly'), ('FRM', 'Yearly')], default='IMG', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(default='http://google.co.uk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
