# Generated by Django 2.2.1 on 2019-07-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0005_auto_20190708_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image'), (' VID', 'Video'), ('FRM', 'Yearly')], max_length=3),
        ),
    ]
