# Generated by Django 2.2.1 on 2019-07-11 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0005_playlist_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='interspersed_source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='screens.Source'),
        ),
    ]
