# Generated by Django 2.2.1 on 2019-07-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0006_auto_20190711_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
