# Generated by Django 2.2.1 on 2019-07-08 15:20

from django.db import migrations, models
import screens.models.source


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0006_auto_20190708_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(null=True, upload_to=screens.models.source.get_file_path),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
