# Generated by Django 2.2.1 on 2019-07-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0007_auto_20190708_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='default',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='screens.Playlist'),
            preserve_default=False,
        ),
    ]
