# Generated by Django 2.2.1 on 2019-08-28 15:41

from django.db import migrations, models
import django.db.models.deletion
import screens.models.source


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0007_source_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistentry',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='screen',
            name='interspersed_source',
            field=models.ForeignKey(blank=True, default=None, help_text='Optional (you probably want an event schedule here)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='screens.Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, help_text='resolution of files should be 1360x768, videos must be mp4', null=True, upload_to=screens.models.source.get_file_path),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('FRM', 'Website')], max_length=3),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, help_text='only required if website type', verbose_name='Website Address'),
        ),
    ]
