# Generated by Django 2.2.1 on 2019-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0008_auto_20190828_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
