# Generated by Django 2.2.1 on 2019-07-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0008_schedule_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='default',
            new_name='default_playlist',
        ),
    ]
