# Generated by Django 3.1.6 on 2021-02-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0009_source_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistentry',
            name='duration',
            field=models.IntegerField(blank=True, default=10, help_text='number of seconds to display source for', null=True),
        ),
    ]
