# Generated by Django 3.1.5 on 2021-02-19 14:54

from django.db import migrations, models
import django.db.models.deletion
import screens.models.source


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0011_auto_20210215_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='last_seen',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='interspersed_source',
            field=models.ForeignKey(blank=True, default=None, help_text='Optional. Plays randomly between other content', null=True, on_delete=django.db.models.deletion.SET_NULL, to='screens.source'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='interspersed_source',
            field=models.ForeignKey(blank=True, default=None, help_text='Optional. Plays randomly between other content', null=True, on_delete=django.db.models.deletion.SET_NULL, to='screens.source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=screens.models.source.get_file_path),
        ),
    ]
