# Generated by Django 3.1.5 on 2021-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0012_auto_20210219_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='online',
        ),
        migrations.AlterField(
            model_name='screen',
            name='last_seen',
            field=models.DateTimeField(),
        ),
    ]
