# Generated by Django 3.1.6 on 2021-05-22 17:45

from django.db import migrations, models
import django.db.models.deletion
import screens.models.source


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0013_auto_20210219_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='interspersed_source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='screens.source'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='interspersed_source',
            field=models.ForeignKey(blank=True, default=None, help_text='Optional (you probably want an event schedule here)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='screens.source'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, help_text='resolution of files should be 1360x768, videos must be mp4', null=True, upload_to=screens.models.source.get_file_path),
        ),
        migrations.DeleteModel(
            name='SchedulePart',
        ),
    ]
