# Generated by Django 3.2.4 on 2021-08-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0015_source_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerule',
            name='end_time',
            field=models.TimeField(help_text='End times before the start time will wrap around into the day after'),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='start_time',
            field=models.TimeField(help_text='Matching start and end times will create the end time 1 second before the start time'),
        ),
    ]
