# Generated by Django 3.2.4 on 2021-08-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0015_source_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inheriting_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents_list', to='screens.playlist')),
                ('super_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children_list', to='screens.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='All sources that would be played by these playlists will be included in this one too.', related_name='children', through='screens.PlaylistRelation', to='screens.Playlist'),
        ),
    ]
