# Generated by Django 4.0.2 on 2022-11-23 18:32

from django.db import migrations, models
import screens.models.source


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0018_alter_source_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='exclude_from_play_all',
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, help_text='resolution of files should be 1920x1080, videos must be mp4', null=True, upload_to=screens.models.source.get_file_path),
        ),
    ]
