# Generated by Django 4.2.29 on 2026-03-05 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("screens", "0019_remove_source_exclude_from_play_all_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
