# Generated by Django 4.2.29 on 2026-03-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0020_source_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
