# Generated by Django 4.2.29 on 2026-05-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0021_source_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='interspersed_source',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='plays_everything',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='interspersed_source',
        ),
        migrations.AddField(
            model_name='playlist',
            name='interspersed_playlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='screens.playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='interspersed_rate',
            field=models.PositiveIntegerField(default=1, help_text='number of base playlist items to play before one item from the interspersed playlist'),
        ),
        migrations.AddField(
            model_name='screen',
            name='interspersed_playlist',
            field=models.ForeignKey(blank=True, default=None, help_text="Optional playlist interspersed into the screen's playlist", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='screens.playlist'),
        ),
        migrations.AddField(
            model_name='screen',
            name='interspersed_rate',
            field=models.PositiveIntegerField(default=1, help_text='number of items to play before one item from the interspersed playlist'),
        ),
    ]
