# Generated by Django 5.2.14 on 2026-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0022_remove_playlist_interspersed_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='All sources that would be played by these playlists will be included in this one too.', related_name='children', through='screens.PlaylistRelation', through_fields=('inheriting_list', 'super_list'), to='screens.playlist'),
        ),
        migrations.AlterField(
            model_name='source',
            name='playlists',
            field=models.ManyToManyField(blank=True, help_text='All sources that would be played by these playlists will be included in this one too.', related_name='sources', through='screens.PlaylistEntry', through_fields=('source', 'playlist'), to='screens.playlist'),
        ),
    ]
