# Generated by Django 5.2.14 on 2026-08-12 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0023_alter_playlist_parents_alter_source_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='interspersed_playlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interspersed_into', to='screens.playlist'),
        ),
    ]
