# Generated by Django 2.2.1 on 2019-09-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_schedules', '0004_event_cancelled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time', 'end_time']},
        ),
    ]
